<h1><center>CMPE 462 - Project 2<br>Implementing an SVM Classifier<br>Due: May 18, 2020, 23:59</center></h1>

* **Student ID1:** 2015400084
* **Student ID2:** 2015400030
* **Student ID3:** 2017400294

## Overview

In this project, you are going to implement SVM. For this purpose, a data set (data.mat) is given to you. You can load the mat dataset into Python using the function `loadmat` in `Scipy.io`. When you load the data, you will obtain a dictionary object, where `X` stores the data matrix and `Y` stores the labels. You can use the first 150 samples for training and the rest for testing. In this project, you will use the software package [`LIBSVM`](http://www.csie.ntu.edu.tw/~cjlin/libsvm/) to implement SVM. Note that `LIBSVM` has a [`Python interface`](https://github.com/cjlin1/libsvm/tree/master/python), so you can call the SVM functions in Python. 

In [2]:
import scipy.io as sio

In [3]:
data = sio.loadmat('data.mat')

In [4]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Mon Nov 07 21:39:10 2011',
 '__version__': '1.0',
 '__globals__': [],
 'Y': array([[ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [-1],
  

In [5]:
X = data['X']

In [6]:
X_train = X[0:150, :]
X_test = X[150:, :]

In [7]:
y = data['Y']

In [8]:
y_train = y[0:150, 0]
y_test = y[150:, 0]

In [9]:
#pip install libsvm

## Task 1 - 30 pts

Train a hard margin linear SVM and report both train and test classification accuracy.

In [10]:
from libsvm.svmutil import *
import numpy as np

In [11]:
hard_margin_linear_svm = svm_train(y_train, X_train, "-t 0 -c 1e10")

In [12]:
# Train classification accuracy
p_label, p_acc, p_val = svm_predict(y_train, X_train, hard_margin_linear_svm)

Accuracy = 74.6667% (112/150) (classification)


In [13]:
# Test classification accuracy
p_label, p_acc, p_val = svm_predict(y_test, X_test, hard_margin_linear_svm)

Accuracy = 77.5% (93/120) (classification)


## Task 2 - 40 pts

Train soft margin SVM for different values of the parameter $C$, and with different kernel functions. Systematically report your results. For instance, report the performances of different kernels for a fixed $C$, then report the performance for different $C$ values for a fixed kernel, and so on.

In [14]:
soft_margin_1_linear_svm = svm_train(y_train, X_train, "-t 0 -c 1")

In [15]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_1_linear_svm)

Accuracy = 86.6667% (130/150) (classification)


In [16]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_1_linear_svm)

Accuracy = 85% (102/120) (classification)


In [17]:
soft_margin_10_linear_svm = svm_train(y_train, X_train, "-t 0 -c 10")

In [18]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_10_linear_svm)

Accuracy = 88.6667% (133/150) (classification)


In [19]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_10_linear_svm)

Accuracy = 81.6667% (98/120) (classification)


In [20]:
soft_margin_100_linear_svm = svm_train(y_train, X_train, "-t 0 -c 100")

In [21]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_100_linear_svm)

Accuracy = 88.6667% (133/150) (classification)


In [22]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_100_linear_svm)

Accuracy = 81.6667% (98/120) (classification)


In [23]:
soft_margin_1000_linear_svm = svm_train(y_train, X_train, "-t 0 -c 1000")

In [24]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_1000_linear_svm)

Accuracy = 90% (135/150) (classification)


In [25]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_1000_linear_svm)

Accuracy = 81.6667% (98/120) (classification)


In [26]:
soft_margin_polynomial_linear_svm = svm_train(y_train, X_train, "-t 1 -c 1")

In [27]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_polynomial_linear_svm)

Accuracy = 86% (129/150) (classification)


In [28]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_polynomial_linear_svm)

Accuracy = 82.5% (99/120) (classification)


In [29]:
soft_margin_radial_linear_svm = svm_train(y_train, X_train, "-t 2 -c 1")

In [30]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_radial_linear_svm)

Accuracy = 86.6667% (130/150) (classification)


In [31]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_radial_linear_svm)

Accuracy = 84.1667% (101/120) (classification)


In [32]:
soft_margin_sigmoid_linear_svm = svm_train(y_train, X_train, "-t 3 -c 1")

In [33]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_sigmoid_linear_svm)

Accuracy = 82.6667% (124/150) (classification)


In [34]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_sigmoid_linear_svm)

Accuracy = 84.1667% (101/120) (classification)


## Task 3 - 15 pts

Please report how the number of support vectors changes as the value of $C$ increases (while all other parameters remain the same). Discuss whether your observations match the theory.

In [191]:
len(svm_train(y_train, X_train, "-t 0 -c 1000").get_SV())

49

In [190]:
len(svm_train(y_train, X_train, "-t 0 -c 500").get_SV())

49

In [182]:
len(svm_train(y_train, X_train, "-t 0 -c 100").get_SV())

50

In [183]:
len(svm_train(y_train, X_train, "-t 0 -c 10").get_SV())

51

In [184]:
len(svm_train(y_train, X_train, "-t 0 -c 1").get_SV())

58

In [185]:
len(svm_train(y_train, X_train, "-t 0 -c 0.1").get_SV())

74

In [186]:
len(svm_train(y_train, X_train, "-t 0 -c 0.01").get_SV())

118

In [187]:
len(svm_train(y_train, X_train, "-t 0 -c 0.001").get_SV())

140

In [188]:
len(svm_train(y_train, X_train, "-t 0 -c 0.0001").get_SV())

140

The C parameter tells the SVM optimization how much you want to avoid misclassifying each training example. For large values of C, the optimization will choose a smaller-margin hyperplane if that hyperplane does a better job of getting all the training points classified correctly. Conversely, a very small value of C will cause the optimizer to look for a larger-margin separating hyperplane, even if that hyperplane misclassifies more points. For very tiny values of C, you should get misclassified examples, often even if your training data is linearly separable.

## Task 4 - 15 pts

Please investigate the changes in the hyperplane when you remove one of the support vectors, vs., one data point that is not a support vector.

In [165]:
def get_weights(model):
    matrix = []
    for vector in model.get_SV():
        vec = []
        for i in range(1,14):
            if i in vector:
                vec.append(vector[i])
            else:
                vec.append(0)
        matrix.append(vec)
    matrix = np.array(matrix)
    
    vector = []
    for val in model.get_sv_coef():
        vector.append(val[0])
    vector = np.array(vector)
    
    return np.dot(vector, matrix)

In [167]:
get_weights(soft_margin_1_linear_svm)

array([-0.47637751,  0.39813231,  0.86713369,  0.57366213,  0.32304567,
        0.10008082,  0.05139059, -0.95512925,  0.07086555,  0.00576303,
        0.24894908,  1.82218655,  0.5129991 ])

In [175]:
ind1 = soft_margin_1_linear_svm.get_sv_indices()[0]

In [176]:
# 58
soft_margin_removed_svm = svm_train(np.delete(y_train, ind1, axis=0), \
                        np.delete(X_train, ind1, axis=0), "-t 0 -c 1")

In [177]:
get_weights(soft_margin_removed_svm)

array([-2.94880396e-01,  4.21184358e-01,  9.26642823e-01,  5.89842928e-01,
        3.48248290e-01,  7.59411670e-02, -1.41871622e-03, -1.02161821e+00,
        1.01050049e-01, -1.44539506e-01,  3.02006450e-01,  1.81590860e+00,
        5.11221871e-01])

In [178]:
indice_list =  [x for x in range(0,150)]

In [179]:
ind2  = list(set(indice_list) - set(soft_margin_1_linear_svm.get_sv_indices()))[0]

In [180]:
# 62
soft_margin_removed_point = svm_train(np.delete(y_train, ind2, axis=0), \
                                      np.delete(X_train, ind2, axis=0), "-t 0 -c 1")

In [181]:
get_weights(soft_margin_removed_point)

array([-0.47637751,  0.39813231,  0.86713369,  0.57366213,  0.32304567,
        0.10008082,  0.05139059, -0.95512925,  0.07086555,  0.00576303,
        0.24894908,  1.82218655,  0.5129991 ])

For a general kernel it is difficult to interpret the SVM weights, however for the linear SVM there actually is a useful interpretation:

1) Recall that in linear SVM, the result is a hyperplane that separates the classes as best as possible. The weights represent this hyperplane, by giving you the coordinates of a vector which is orthogonal to the hyperplane - these are the coefficients given by svm.coef_. Let's call this vector w.

2) What can we do with this vector? It's direction gives us the predicted class, so if you take the dot product of any point with the vector, you can tell on which side it is: if the dot product is positive, it belongs to the positive class, if it is negative it belongs to the negative class.

### Bonus Task - 10 pts

Use Python and [CVXOPT](http://cvxopt.org) QP solver to implement the hard margin SVM. 