<h1><center>CMPE 462 - Project 2<br>Implementing an SVM Classifier<br>Due: May 18, 2020, 23:59</center></h1>

* **Student ID1:** 2015400084
* **Student ID2:** 2015400030
* **Student ID3:** 2017400294

## Overview

In this project, you are going to implement SVM. For this purpose, a data set (data.mat) is given to you. You can load the mat dataset into Python using the function `loadmat` in `Scipy.io`. When you load the data, you will obtain a dictionary object, where `X` stores the data matrix and `Y` stores the labels. You can use the first 150 samples for training and the rest for testing. In this project, you will use the software package [`LIBSVM`](http://www.csie.ntu.edu.tw/~cjlin/libsvm/) to implement SVM. Note that `LIBSVM` has a [`Python interface`](https://github.com/cjlin1/libsvm/tree/master/python), so you can call the SVM functions in Python. 

In [1]:
import scipy.io as sio

In [2]:
data = sio.loadmat('data.mat')

In [3]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Mon Nov 07 21:39:10 2011',
 '__version__': '1.0',
 '__globals__': [],
 'Y': array([[ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [-1],
  

In [4]:
X = data['X']

(270, 13)

In [5]:
X_train = X[0:150, :]
X_test = X[150:, :]

In [6]:
y = data['Y']

In [7]:
y_train = y[0:150, 0]
y_test = y[150:, 0]

In [8]:
#pip install libsvm

## Task 1 - 30 pts

Train a hard margin linear SVM and report both train and test classification accuracy.

In [9]:
from libsvm.svmutil import *
import numpy as np

In [10]:
hard_margin_linear_svm = svm_train(y_train, X_train, "-t 0 -c 1e10")

In [11]:
# Train classification accuracy
p_label, p_acc, p_val = svm_predict(y_train, X_train, hard_margin_linear_svm)

Accuracy = 74.6667% (112/150) (classification)


In [12]:
# Test classification accuracy
p_label, p_acc, p_val = svm_predict(y_test, X_test, hard_margin_linear_svm)

Accuracy = 77.5% (93/120) (classification)


## Task 2 - 40 pts

Train soft margin SVM for different values of the parameter $C$, and with different kernel functions. Systematically report your results. For instance, report the performances of different kernels for a fixed $C$, then report the performance for different $C$ values for a fixed kernel, and so on.

In [60]:
soft_margin_1_linear_svm = svm_train(y_train, X_train, "-t 0 -c 1")

In [14]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_1_linear_svm)

Accuracy = 86.6667% (130/150) (classification)


In [15]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_1_linear_svm)

Accuracy = 85% (102/120) (classification)


In [16]:
soft_margin_10_linear_svm = svm_train(y_train, X_train, "-t 0 -c 10")

In [17]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_10_linear_svm)

Accuracy = 88.6667% (133/150) (classification)


In [18]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_10_linear_svm)

Accuracy = 81.6667% (98/120) (classification)


In [19]:
soft_margin_100_linear_svm = svm_train(y_train, X_train, "-t 0 -c 100")

In [20]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_100_linear_svm)

Accuracy = 88.6667% (133/150) (classification)


In [21]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_100_linear_svm)

Accuracy = 81.6667% (98/120) (classification)


In [22]:
soft_margin_1000_linear_svm = svm_train(y_train, X_train, "-t 0 -c 1000")

In [23]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_1000_linear_svm)

Accuracy = 90% (135/150) (classification)


In [24]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_1000_linear_svm)

Accuracy = 81.6667% (98/120) (classification)


In [25]:
soft_margin_polynomial_linear_svm = svm_train(y_train, X_train, "-t 1 -c 1")

In [26]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_polynomial_linear_svm)

Accuracy = 86% (129/150) (classification)


In [27]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_polynomial_linear_svm)

Accuracy = 82.5% (99/120) (classification)


In [28]:
soft_margin_radial_linear_svm = svm_train(y_train, X_train, "-t 2 -c 1")

In [29]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_radial_linear_svm)

Accuracy = 86.6667% (130/150) (classification)


In [30]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_radial_linear_svm)

Accuracy = 84.1667% (101/120) (classification)


In [31]:
soft_margin_sigmoid_linear_svm = svm_train(y_train, X_train, "-t 3 -c 1")

In [32]:
p_label, p_acc, p_val = svm_predict(y_train, X_train, soft_margin_sigmoid_linear_svm)

Accuracy = 82.6667% (124/150) (classification)


In [33]:
p_label, p_acc, p_val = svm_predict(y_test, X_test, soft_margin_sigmoid_linear_svm)

Accuracy = 84.1667% (101/120) (classification)


## Task 3 - 15 pts

Please report how the number of support vectors changes as the value of $C$ increases (while all other parameters remain the same). Discuss whether your observations match the theory.

In [34]:
len(svm_train(y_train, X_train, "-t 0 -c 1000").get_SV())

49

In [35]:
len(svm_train(y_train, X_train, "-t 0 -c 500").get_SV())

49

In [36]:
len(svm_train(y_train, X_train, "-t 0 -c 100").get_SV())

50

In [37]:
len(svm_train(y_train, X_train, "-t 0 -c 10").get_SV())

51

In [38]:
len(svm_train(y_train, X_train, "-t 0 -c 1").get_SV())

58

In [39]:
len(svm_train(y_train, X_train, "-t 0 -c 0.1").get_SV())

74

In [40]:
len(svm_train(y_train, X_train, "-t 0 -c 0.01").get_SV())

118

In [41]:
len(svm_train(y_train, X_train, "-t 0 -c 0.001").get_SV())

140

In [42]:
len(svm_train(y_train, X_train, "-t 0 -c 0.0001").get_SV())

140

The C parameter tells the SVM optimization how much you want to avoid misclassifying each training example. For large values of C, the optimization will choose a smaller-margin hyperplane if that hyperplane does a better job of getting all the training points classified correctly. Conversely, a very small value of C will cause the optimizer to look for a larger-margin separating hyperplane, even if that hyperplane misclassifies more points. For very tiny values of C, you should get misclassified examples, often even if your training data is linearly separable.

## Task 4 - 15 pts

Please investigate the changes in the hyperplane when you remove one of the support vectors, vs., one data point that is not a support vector.

In [43]:
def get_weights(model):
    matrix = []
    for vector in model.get_SV():
        vec = []
        for i in range(1,14):
            if i in vector:
                vec.append(vector[i])
            else:
                vec.append(0)
        matrix.append(vec)
    matrix = np.array(matrix)
    
    vector = []
    for val in model.get_sv_coef():
        vector.append(val[0])
    vector = np.array(vector)
    
    return np.dot(vector, matrix)

# With complete train data:

In [44]:
get_weights(soft_margin_1_linear_svm)

array([-0.47637751,  0.39813231,  0.86713369,  0.57366213,  0.32304567,
        0.10008082,  0.05139059, -0.95512925,  0.07086555,  0.00576303,
        0.24894908,  1.82218655,  0.5129991 ])

In [45]:
soft_margin_1_linear_svm.get_sv_coef()

[(1.0,),
 (1.0,),
 (1.0,),
 (0.36189302363423326,),
 (1.0,),
 (1.0,),
 (0.6762643033199851,),
 (1.0,),
 (0.8772694011914622,),
 (1.0,),
 (0.7789663308904083,),
 (1.0,),
 (1.0,),
 (1.0,),
 (0.17167090298683027,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (0.87244518201531,),
 (1.0,),
 (1.0,),
 (1.0,),
 (-0.980256855449567,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-0.5093032053086625,),
 (-0.49866907563257956,),
 (-1.0,),
 (-1.0,),
 (-0.20702457212155462,),
 (-1.0,),
 (-0.37664950414847226,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-0.08297207991166626,),
 (-1.0,),
 (-0.9208403662181653,),
 (-1.0,),
 (-0.16279348524755968,),
 (-1.0,),
 (-1.0,),
 (-1.0,)]

# With one data point that is not a support vector removed:

In [46]:
indice_list =  [x for x in range(0,150)]

In [47]:
nonSupportIndex  = list(set(indice_list) - set(soft_margin_1_linear_svm.get_sv_indices()))[0]

In [48]:
# 62
soft_margin_removed_point = svm_train(np.delete(y_train, nonSupportIndex, axis=0), \
                                      np.delete(X_train, nonSupportIndex, axis=0), "-t 0 -c 1")

In [49]:
get_weights(soft_margin_removed_point)

array([-0.47637751,  0.39813231,  0.86713369,  0.57366213,  0.32304567,
        0.10008082,  0.05139059, -0.95512925,  0.07086555,  0.00576303,
        0.24894908,  1.82218655,  0.5129991 ])

In [50]:
soft_margin_removed_point.get_sv_coef()

[(1.0,),
 (1.0,),
 (1.0,),
 (0.36189302363423326,),
 (1.0,),
 (1.0,),
 (0.6762643033199851,),
 (1.0,),
 (0.8772694011914622,),
 (1.0,),
 (0.7789663308904083,),
 (1.0,),
 (1.0,),
 (1.0,),
 (0.17167090298683027,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (0.87244518201531,),
 (1.0,),
 (1.0,),
 (1.0,),
 (-0.980256855449567,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-0.5093032053086625,),
 (-0.49866907563257956,),
 (-1.0,),
 (-1.0,),
 (-0.20702457212155462,),
 (-1.0,),
 (-0.37664950414847226,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-0.08297207991166626,),
 (-1.0,),
 (-0.9208403662181653,),
 (-1.0,),
 (-0.16279348524755968,),
 (-1.0,),
 (-1.0,),
 (-1.0,)]

# With a support vector removed:

In [51]:
supportIndex = soft_margin_1_linear_svm.get_sv_indices()[0]

In [52]:
# 58
soft_margin_removed_svm = svm_train(np.delete(y_train, supportIndex, axis=0), \
                        np.delete(X_train, supportIndex, axis=0), "-t 0 -c 1")

In [53]:
get_weights(soft_margin_removed_svm)

array([-2.94880396e-01,  4.21184358e-01,  9.26642823e-01,  5.89842928e-01,
        3.48248290e-01,  7.59411670e-02, -1.41871622e-03, -1.02161821e+00,
        1.01050049e-01, -1.44539506e-01,  3.02006450e-01,  1.81590860e+00,
        5.11221871e-01])

In [54]:
soft_margin_removed_svm.get_sv_coef()

[(1.0,),
 (1.0,),
 (0.44117335103867744,),
 (1.0,),
 (0.9231704648675159,),
 (1.0,),
 (1.0,),
 (0.835696685446032,),
 (1.0,),
 (0.4717685867177793,),
 (1.0,),
 (0.18436835748691904,),
 (1.0,),
 (1.0,),
 (1.0,),
 (0.2576566850212111,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (1.0,),
 (-0.6775304371000335,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-0.5754705949725748,),
 (-0.23889945299187854,),
 (-1.0,),
 (-1.0,),
 (-0.3509560225159673,),
 (-1.0,),
 (-0.5206475331678161,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-1.0,),
 (-0.36773567162603826,),
 (-0.6162956331932118,),
 (-1.0,),
 (-1.0,),
 (-0.7662987850106137,)]

### Bonus Task - 10 pts

Use Python and [CVXOPT](http://cvxopt.org) QP solver to implement the hard margin SVM. 